plugins {
    id 'java'
    id "io.qameta.allure" version "2.11.2"
}

group = 'com.phonebook'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

allure {
    version = '2.24.0'
}

configurations.all {
    resolutionStrategy {
        force 'org.apache.commons:commons-lang3:3.14.0'
        force 'commons-codec:commons-codec:1.15'
    }
}

dependencies {
    // ===== TestNG + Allure =====
    testImplementation 'org.testng:testng:7.11.0'
    testImplementation 'io.qameta.allure:allure-testng:2.24.0'
    testImplementation 'io.qameta.allure:allure-java-commons:2.24.0'

    // ===== SLF4J + Logback =====
    implementation 'org.slf4j:slf4j-api:2.0.7'
    implementation 'ch.qos.logback:logback-classic:1.4.11'

    // ===== Selenium =====
    implementation 'org.seleniumhq.selenium:selenium-java:4.25.0'

    // ===== REST Assured =====
    implementation 'io.rest-assured:rest-assured:5.4.0'
    implementation 'com.google.code.gson:gson:2.10.1'

    // ===== Mobile (Appium) =====
    implementation 'io.appium:java-client:9.2.2'

    // ===== Utils =====
    implementation 'net.datafaker:datafaker:2.5.2'
    implementation 'commons-io:commons-io:2.18.0'
    implementation 'commons-codec:commons-codec:1.15'

    // ===== Lombok =====
    compileOnly 'org.projectlombok:lombok:1.18.28'
    annotationProcessor 'org.projectlombok:lombok:1.18.28'
    testCompileOnly 'org.projectlombok:lombok:1.18.28'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.28'
}

tasks.withType(Test).configureEach {
    useTestNG()
    jvmArgs = ['--add-opens', 'java.base/java.lang=ALL-UNNAMED']
}