version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: phonebook_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root1234
      MYSQL_DATABASE: phonebook
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql